services:
  phpmyadmin:
    container_name: phpmyadmin
    image: phpmyadmin/phpmyadmin:latest
    restart: always
    ports:
      - 8081:80
    networks:
      - backend

  db:
    container_name: mysql
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: interview123
    ports:
      - '3306:3306'
    networks:
      - backend
    volumes:
      - db-vol:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql

  backend:
    container_name: backend_api
    restart: always
    build:
      context: backend
      dockerfile: Dockerfile
    ports:
      - '8080:8080'
    networks:
      - backend
    depends_on:
      - db

  frontend:
    container_name: next_frontend
    volumes:
      - ./frontend:/usr/src/app # Mapujemy folder lokalny frontend do kontenera
      - /usr/src/app/node_modules
    restart: unless-stopped
    build:
      context: ./frontend
      dockerfile: Dockerfile
    networks:
      - backend
    ports:
      - '3000:3000'
    depends_on:
      - backend
    command: ['npm', 'run', 'dev']
    environment:
      - CHOKIDAR_USEPOLLING=true

networks:
  backend:

volumes:
  db-vol:
